# Generated by Django 4.2.7 on 2023-11-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0002_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
