# Generated by Django 4.2.7 on 2024-01-29 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notarius', '0004_report_appraiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeOfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purposeOfAssessment', models.CharField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='appraiser',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик'),
        ),
        migrations.AlterField(
            model_name='report',
            name='conrtractDate',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='report',
            name='contractNumber',
            field=models.IntegerField(unique=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='report',
            name='purposeOfAssessment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='notarius.purposeofassessment', verbose_name='Цель оценки'),
        ),
    ]
