# Generated by Django 4.2.7 on 2024-01-29 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0006_clienttype_alter_purposeofassessment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientFullName', models.CharField(null=True)),
                ('clientAdress', models.CharField(null=True)),
            ],
            options={
                'verbose_name': 'Тип Заказчика',
                'verbose_name_plural': 'Тип Заказчика',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='clientData',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientdata', to='notarius.clientdata', verbose_name='Данные заказчика'),
        ),
    ]
