# Generated by Django 4.2.7 on 2024-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0007_clientdata_report_clientdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='clientData',
        ),
        migrations.AddField(
            model_name='report',
            name='clientName',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.DeleteModel(
            name='ClientData',
        ),
    ]
