# Generated by Django 4.2.7 on 2024-01-29 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0008_remove_report_clientdata_report_clientname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='clientAdress',
            field=models.TextField(null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='report',
            name='clientPasportDate',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='report',
            name='clientPasportGov',
            field=models.CharField(max_length=255, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='report',
            name='clientPasportNum',
            field=models.CharField(max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='report',
            name='clientPasportSer',
            field=models.CharField(max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='report',
            name='objectOfAssessmentModel',
            field=models.CharField(max_length=255, null=True, verbose_name='Марка/модель автомобиля'),
        ),
        migrations.AddField(
            model_name='report',
            name='objectOfAssessmentVIN',
            field=models.CharField(max_length=255, null=True, verbose_name='VIN автомобиля'),
        ),
        migrations.AddField(
            model_name='report',
            name='objectOfAssessmentYear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='Марка/модель автомобиля'),
        ),
    ]
