# Generated by Django 4.2.7 on 2024-01-30 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0009_report_clientadress_report_clientpasportdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purposeofassessment',
            name='purposeOfAssessment',
            field=models.CharField(null=True, verbose_name='Цель оценки'),
        ),
        migrations.AlterField(
            model_name='report',
            name='objectOfAssessmentYear',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска автомобиля'),
        ),
        migrations.AlterField(
            model_name='report',
            name='purposeOfAssessment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purpose', to='notarius.purposeofassessment', verbose_name='Цель оценки'),
        ),
    ]
