# Generated by Django 4.2.7 on 2024-01-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0010_alter_purposeofassessment_purposeofassessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purposeofassessment',
            old_name='purposeOfAssessment',
            new_name='purposeOfAssessment1',
        ),
    ]
