# Generated by Django 4.2.7 on 2024-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0011_rename_purposeofassessment_purposeofassessment_purposeofassessment1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName1', models.CharField(max_length=255, null=True, verbose_name='ФИО клиента1')),
                ('clientAdress1', models.TextField(null=True, verbose_name='Адрес клиента1')),
                ('clientPasportSer1', models.CharField(max_length=4, null=True, verbose_name='Серия паспорта1')),
                ('clientPasportNum1', models.CharField(max_length=6, null=True, verbose_name='Номер паспорта1')),
                ('clientPasportDate1', models.DateField(null=True, verbose_name='Дата выдачи паспорта1')),
                ('clientPasportGov1', models.CharField(max_length=255, null=True, verbose_name='Кем выдан паспорт1')),
            ],
        ),
        migrations.AlterField(
            model_name='purposeofassessment',
            name='purposeOfAssessment1',
            field=models.CharField(default=1, verbose_name='Цель оценки'),
        ),
    ]
