# Generated by Django 4.2.7 on 2024-02-02 08:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0012_clientpersondata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectOfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectOfAssessmentModel', models.CharField(max_length=255, null=True, verbose_name='Марка/модель автомобиля')),
                ('objectOfAssessmentYear', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='Год выпуска автомобиля')),
                ('objectOfAssessmentVIN', models.CharField(max_length=255, null=True, verbose_name='VIN автомобиля')),
            ],
        ),
        migrations.RenameField(
            model_name='clientpersondata',
            old_name='clientAdress1',
            new_name='clientAdress',
        ),
        migrations.RenameField(
            model_name='clientpersondata',
            old_name='clientPasportDate1',
            new_name='clientPasportDate',
        ),
        migrations.RenameField(
            model_name='clientpersondata',
            old_name='clientPasportGov1',
            new_name='clientPasportGov',
        ),
        migrations.RenameField(
            model_name='clientpersondata',
            old_name='clientPasportNum1',
            new_name='clientPasportNum',
        ),
        migrations.RenameField(
            model_name='clientpersondata',
            old_name='clientPasportSer1',
            new_name='clientPasportSer',
        ),
        migrations.RemoveField(
            model_name='clientpersondata',
            name='clientName1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='clientAdress',
        ),
        migrations.RemoveField(
            model_name='report',
            name='clientPasportDate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='clientPasportGov',
        ),
        migrations.RemoveField(
            model_name='report',
            name='clientPasportNum',
        ),
        migrations.RemoveField(
            model_name='report',
            name='clientPasportSer',
        ),
        migrations.RemoveField(
            model_name='report',
            name='objectOfAssessmentModel',
        ),
        migrations.RemoveField(
            model_name='report',
            name='objectOfAssessmentVIN',
        ),
        migrations.RemoveField(
            model_name='report',
            name='objectOfAssessmentYear',
        ),
        migrations.AddField(
            model_name='report',
            name='clientPersonData',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientdata', to='notarius.clientpersondata', verbose_name='Данные клиента'),
        ),
        migrations.AlterField(
            model_name='report',
            name='clientName',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО клиента1'),
        ),
        migrations.AddField(
            model_name='report',
            name='objectOfAssessment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectofassessment', to='notarius.objectofassessment', verbose_name='Объект оценки'),
        ),
    ]
