# Generated by Django 4.2.7 on 2024-02-06 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0013_objectofassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTechnicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortTechnicalCondition', models.CharField(null=True, verbose_name='Краткое описание технического состояния')),
                ('fullTechnicalCondition', models.CharField(null=True, verbose_name='Полное описание технического состояния')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientpersondata',
            options={'verbose_name': 'Данные Заказчика', 'verbose_name_plural': 'Данные Заказчика'},
        ),
        migrations.AlterModelOptions(
            name='objectofassessment',
            options={'verbose_name': 'Объект оценки', 'verbose_name_plural': 'Объекты оценки'},
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='engine_power',
            field=models.CharField(max_length=10, null=True, verbose_name='Мощность двигателя, л.с. (кВт)'),
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='objectRegistrationNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='Государственный рег. знак'),
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='physicalDeterioration',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Физический износ, %'),
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='vehicleCategory',
            field=models.CharField(max_length=2, null=True, verbose_name='Категория транспортного средства'),
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='vehicleColor',
            field=models.CharField(max_length=15, null=True, verbose_name='Цвет транспортного средства'),
        ),
        migrations.AddField(
            model_name='report',
            name='dateOfAssessment',
            field=models.DateField(null=True, verbose_name='Дата оценки'),
        ),
        migrations.AddField(
            model_name='report',
            name='dateOfReport',
            field=models.DateField(null=True, verbose_name='Дата составления отчета'),
        ),
        migrations.AddField(
            model_name='report',
            name='documentsOfReport',
            field=models.TextField(null=True, verbose_name='Перечень используемых документов'),
        ),
        migrations.AddField(
            model_name='report',
            name='reportNumber',
            field=models.IntegerField(null=True, verbose_name='Номер отчета'),
        ),
        migrations.AlterField(
            model_name='clientpersondata',
            name='clientAdress',
            field=models.TextField(null=True, verbose_name='Адрес клиента'),
        ),
        migrations.AlterField(
            model_name='clientpersondata',
            name='clientPasportDate',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='clientpersondata',
            name='clientPasportGov',
            field=models.CharField(max_length=255, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AlterField(
            model_name='clientpersondata',
            name='clientPasportNum',
            field=models.CharField(max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='clientpersondata',
            name='clientPasportSer',
            field=models.CharField(max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='clientName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО клиента'),
        ),
        migrations.AddField(
            model_name='objectofassessment',
            name='vehicleTechnicalCondition',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicletechnicalcondition', to='notarius.vehicletechnicalcondition', verbose_name='Техническое состояние объекта оценки'),
        ),
    ]
