# Generated by Django 4.2.7 on 2024-02-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0015_analogues_report_analogue1_report_analogue2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogues',
            name='offerDate',
            field=models.DateField(null=True, verbose_name='Дата объявления'),
        ),
    ]
