# Generated by Django 4.2.7 on 2024-02-09 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0018_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='objectTotalCost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Итоговая стоимость'),
        ),
    ]
