# Generated by Django 4.2.7 on 2024-02-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0019_report_objecttotalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogues',
            name='analogueAdjustments1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogueadjustments1', to='notarius.adjustments', verbose_name='Корректировки 1 аналога'),
        ),
        migrations.AddField(
            model_name='analogues',
            name='analogueAdjustments2',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogueadjustments2', to='notarius.adjustments', verbose_name='Корректировки 2 аналога'),
        ),
        migrations.AddField(
            model_name='analogues',
            name='analogueAdjustments3',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogueadjustments3', to='notarius.adjustments', verbose_name='Корректировки 3 аналога'),
        ),
    ]
