# Generated by Django 4.2.7 on 2024-02-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0020_analogues_analogueadjustments1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogues',
            name='analogueAdjustments1',
        ),
        migrations.RemoveField(
            model_name='analogues',
            name='analogueAdjustments2',
        ),
        migrations.RemoveField(
            model_name='analogues',
            name='analogueAdjustments3',
        ),
        migrations.AddField(
            model_name='analogues',
            name='analogueAdjustments',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analogueadjustments', to='notarius.adjustments', verbose_name='Корректировки аналога'),
        ),
    ]
