# Generated by Django 4.2.7 on 2024-02-14 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notarius', '0021_remove_analogues_analogueadjustments1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-pk'], 'verbose_name': 'Список отчетов', 'verbose_name_plural': 'Список отчетов'},
        ),
        migrations.AddField(
            model_name='report',
            name='objectTotalCostWord',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='Итоговая стоимость словами'),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='analogueAdjustedDiscount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Скорректированная после торга цена'),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='analogueAdjustedTechnicalCondition',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Скорректированная после износа цена'),
        ),
        migrations.AlterField(
            model_name='adjustments',
            name='analogueAveragePrice',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='Средневзвешенная цена'),
        ),
    ]
